platform :ios, '8.0'

target 'AppStoreClone' do

  pod 'react-native-navigation', :path => '../node_modules/react-native-navigation'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'DevSupport',
  ]

  target 'AppStoreCloneTests' do
    inherit! :search_paths
  end
end
