fastlane_version "2.69.2"

default_platform :ios

platform :ios do

  before_all do
  end

  desc "Continous Delivery build to TestFlight"
  lane :travis do
    match(
      type: "appstore",
      readonly: true
    )
    path = "./AppStoreClone.xcodeproj"
    increment_build_number(xcodeproj: path)
    version = get_version_number(xcodeproj: path)
    build = get_build_number(xcodeproj: path)
    gym(
      scheme: "AppStoreClone",
      workspace: "./AppStoreClone.xcworkspace",
      output_directory: "ios/build",
      configuration: "Release",
      export_method: "app-store"
    )
    testflight(
      skip_waiting_for_build_processing: true
    )
    commit_version_bump(
      xcodeproj: path,
      message: "Version #{version} (build #{build}) [travisbuild] [skip ci]"
    )
    add_git_tag(tag: "v#{version}-#{build}")
    push_to_git_remote
    slack(
      message: "Successfully uploaded #{version} (build #{build}) to TestFlight"
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end

end
